// sidebars.js
// One sidebar with all DevOps topics as collapsible categories.
// Add new posts by creating a .md file in the right folder —
// Docusaurus picks it up automatically via autogenerated.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  devopsSidebar: [

    // ── Monitoring ────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '📊 Monitoring',
      link: { type: 'doc', id: 'monitoring/overview' },
      items: [{ type: 'autogenerated', dirName: 'monitoring' }],
    },

    // ── Docker ────────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '🐳 Docker',
      link: { type: 'doc', id: 'docker/overview' },
      items: [{ type: 'autogenerated', dirName: 'docker' }],
    },

    // ── AWS ───────────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '☁️ AWS',
      link: { type: 'doc', id: 'aws/overview' },
      items: [{ type: 'autogenerated', dirName: 'aws' }],
    },

    // ── GitOps ────────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '🚀 GitOps & EKS',
      link: { type: 'doc', id: 'gitops/overview' },
      items: [{ type: 'autogenerated', dirName: 'gitops' }],
    },

    // ── Linux ─────────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '🖥️ Linux',
      link: { type: 'doc', id: 'linux/overview' },
      items: [{ type: 'autogenerated', dirName: 'linux' }],
    },

    // ── Add a new section: duplicate the block above, change label and dirName
    // Example:
    // {
    //   type: 'category',
    //   label: '⚙️ Kubernetes',
    //   link: { type: 'doc', id: 'kubernetes/overview' },
    //   items: [{ type: 'autogenerated', dirName: 'kubernetes' }],
    // },

  ],
};

export default sidebars;
